# Generated by Django 3.2.5 on 2021-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('Department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Date_of_joining', models.DateField()),
                ('Phote_file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
